#!/usr/bin/env python3
"""
tools/gen_rules.py — generate .claude/rules/<scope>.md from ADR frontmatter.

Mirrors the dashboard/server.py --generate-readme pattern (stdlib-only, no
third-party YAML parser needed — frontmatter is simple key: value syntax).

Rule ID scheme: <SCOPE3>-NNN where SCOPE3 is the first 3 characters of the
scope name uppercased (e.g. scope "capture" → "CAP"), and NNN is a zero-padded
counter within that scope.  Rule IDs are declared in ADR frontmatter
``rule_ids`` lists and are STABLE — never reused, never reordered.

ADR Frontmatter keys (required for inclusion):
  id           — ADR identifier (e.g. "ADR-0006")
  status       — "accepted" | "superseded" (case-insensitive)
  supersedes   — list of ADR IDs this supersedes (may be empty list)
  superseded_by — list of ADR IDs that supersede this (may be empty list)
  scope        — short slug (e.g. "capture", "commits", "pipeline")
  rule_ids     — list of stable rule_ids (e.g. ["CAP-001", "CAP-002"])

ADRs with status "superseded" (or any superseded_by entry) are excluded from
the generated output.  ADRs without frontmatter are skipped gracefully.

Output: .claude/rules/<scope>.md per scope found in non-superseded ADRs.
Header: <!-- GENERATED by tools/gen_rules.py — DO NOT EDIT — regenerate to update -->

Usage:
  python tools/gen_rules.py          # writes all discovered scopes
  python tools/gen_rules.py --check  # dry-run: exits non-zero if output differs
"""

import os
import sys
import glob
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Repo root resolution (mirrors readme_gen._resolve_invoking_repo_root)
# ---------------------------------------------------------------------------

def _resolve_repo_root() -> Path:
    """Resolve the repo root from the invoking worktree's cwd."""
    import subprocess
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5, cwd=os.getcwd(),
        )
        if result.returncode == 0:
            root = Path(result.stdout.strip())
            if root.is_dir():
                return root
    except Exception:
        pass
    # Fallback: script-file parent's parent
    return Path(__file__).resolve().parent.parent


REPO_ROOT = _resolve_repo_root()
DECISIONS_DIR = REPO_ROOT / "decisions"
RULES_DIR = REPO_ROOT / ".claude" / "rules"
GENERATED_HEADER = (
    "<!-- GENERATED by tools/gen_rules.py — DO NOT EDIT — regenerate to update -->\n"
)

# ---------------------------------------------------------------------------
# Frontmatter parser (stdlib, no PyYAML)
# ---------------------------------------------------------------------------

def _parse_frontmatter(text: str) -> dict | None:
    """
    Parse YAML frontmatter from the top of an ADR file.

    Returns a dict of key→value if frontmatter is present, else None.
    Only supports the subset of YAML used in ADR frontmatter:
      - scalar strings (quoted or unquoted)
      - empty lists: []
      - inline list items starting with "  - " lines
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None

    # Find the closing ---
    close_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            close_idx = i
            break
    if close_idx is None:
        return None

    fm_lines = lines[1:close_idx]
    result: dict = {}
    current_key: str | None = None

    for line in fm_lines:
        # List item continuation
        if line.startswith("  - ") and current_key is not None:
            item = line[4:].strip().strip('"').strip("'")
            if not isinstance(result.get(current_key), list):
                result[current_key] = []
            result[current_key].append(item)
            continue

        # Empty list shorthand: key: []
        m = re.match(r'^(\w+):\s*\[\s*\]\s*$', line)
        if m:
            current_key = m.group(1)
            result[current_key] = []
            continue

        # Scalar: key: value
        m = re.match(r'^(\w+):\s*(.*)', line)
        if m:
            current_key = m.group(1)
            val = m.group(2).strip().strip('"').strip("'")
            result[current_key] = val
            continue

    return result


# ---------------------------------------------------------------------------
# ADR discovery
# ---------------------------------------------------------------------------

def _load_adrs() -> list[dict]:
    """
    Load all ADRs in decisions/ that have frontmatter.

    Returns list of dicts with keys:
      path, id, status, supersedes, superseded_by, scope, rule_ids
    """
    adrs = []
    for adr_path in sorted(DECISIONS_DIR.glob("[0-9]*.md")):
        try:
            text = adr_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        fm = _parse_frontmatter(text)
        if fm is None:
            # No frontmatter — skip gracefully
            continue

        # Normalize required keys
        adr_id = str(fm.get("id", "")).strip()
        status = str(fm.get("status", "")).strip().lower()
        supersedes = fm.get("supersedes", [])
        if isinstance(supersedes, str):
            supersedes = [supersedes] if supersedes else []
        superseded_by = fm.get("superseded_by", [])
        if isinstance(superseded_by, str):
            superseded_by = [superseded_by] if superseded_by else []
        scope = str(fm.get("scope", "")).strip()
        rule_ids = fm.get("rule_ids", [])
        if isinstance(rule_ids, str):
            rule_ids = [rule_ids] if rule_ids else []

        if not adr_id or not scope or not rule_ids:
            # Incomplete frontmatter — skip
            continue

        adrs.append({
            "path": adr_path,
            "id": adr_id,
            "status": status,
            "supersedes": supersedes,
            "superseded_by": superseded_by,
            "scope": scope,
            "rule_ids": rule_ids,
        })

    return adrs


def _is_superseded(adr: dict) -> bool:
    """Return True if this ADR is superseded (should be excluded from digest)."""
    if adr["status"] == "superseded":
        return True
    if adr.get("superseded_by"):
        return True
    return False


# ---------------------------------------------------------------------------
# Rule statement extraction
# ---------------------------------------------------------------------------

# Map rule_id prefix to a one-line human-readable statement.
# These statements are derived from the core decisions in each ADR.
# Format: rule_id → one-line statement.
_RULE_STATEMENTS: dict[str, str] = {
    # ADR-0006: forward-work backlog queue
    "CAP-001": (
        "Agents write `captured`-labeled issues for every deferred or "
        "forward-looking item they identify."
    ),
    "CAP-002": (
        "Session continuity is achieved via live-state reconstruction "
        "(git log + open issues + PRs) — no formal handoff document."
    ),
    # ADR-0008: two-tier captured→backlog + backlog-critic
    "CAP-003": (
        "Captured items are auto-evaluated by `backlog-critic`; APPROVE "
        "promotes to `backlog`, BLOCK leaves in `captured` for human review."
    ),
    "CAP-004": (
        "Backlog-critic evaluates four criteria: Actionable, Scoped, "
        "Not-duplicate, Clear — defaulting to BLOCK when uncertain."
    ),
    # ADR-0024: root-cause discipline
    "CAP-005": (
        "Every workflow mistake MUST produce a `captured`-labeled root-cause "
        "capture (rule #13): symptom + root cause + proposed fix."
    ),
    "CAP-006": (
        "Root-cause captures use the 3-section shape: Symptom observed / "
        "Root cause analyzed / Proposed workflow change."
    ),
    # ADR-0063: capture-shape contract
    "CAP-007": (
        "Root-cause captures carry a `root-cause` label alongside `captured` "
        "to make the class mechanically queryable."
    ),
    "CAP-008": (
        "Root-cause section headings are regex-detectable: `**Symptom:**` / "
        "`**Root cause:**` / `**Proposed:**`; evidence is preserved verbatim "
        "before diagnosing (STOP → PRESERVE → DIAGNOSE → FIX → GUARD → RESUME)."
    ),
    # ADR-0002: autonomous merge policy (D9-revised)
    "PIP-001": (
        "Reviewer's APPROVE verdict triggers auto-merge (`gh pr merge --squash`); "
        "BLOCK sends the PR back to the implementer; after N=3 rounds, escalate to human."
    ),
    # ADR-0003: autonomous pipeline + critics
    "PIP-002": (
        "The unit-of-delivery hierarchy is exactly three tiers: PRD (prd-labeled issue) "
        "→ Slice (slice-labeled sub-issue) → PR (closes one slice)."
    ),
    "PIP-003": (
        "The pipeline has five stages: grill-me → to-prd+prd-critic → slicer+slicer-critic "
        "→ implementer+reviewer → qa-plan; every generation stage is paired with an "
        "adversarial critic."
    ),
    "PIP-004": (
        "The human enters the pipeline at exactly two points: `grill-me` (defines what to "
        "build) and `qa-plan` (acceptance test); everything in between is fully autonomous."
    ),
    "PIP-005": (
        "Human-facing stages use skills (orchestrator-owned procedures); autonomous stages "
        "use subagents (isolated-context + task-handed + result-returning)."
    ),
    # ADR-0010: implementer subagent + /ship auto-invoke
    "PIP-006": (
        "A single `implementer` subagent handles all slice types (feat/fix/docs/refactor/"
        "test) uniformly — no specialized variants until data justifies splitting."
    ),
    "PIP-007": (
        "`/ship` auto-invokes the implementer on each posted slice, closing the residual "
        "human-trigger gap and making ADR-0003 D4's no-human-gates property enforceable "
        "end-to-end."
    ),
    "PIP-008": (
        "Orchestrator reads each slice's `Depends on` field, builds the DAG, and runs "
        "independent slices in parallel; sync points are at dependency boundaries."
    ),
    "PIP-009": (
        "On irrecoverable failure (round-3 BLOCK; ambiguous AC; INVALID_INPUT), the "
        "failed slice gets `needs-human`; in-flight parallel slices finish normally; "
        "slices depending on the failed slice stay blocked."
    ),
    "PIP-010": (
        "Implementer's authorized tools: Read, Edit, Write, Bash, Glob, Grep. "
        "Explicitly excluded: Agent (no recursive subagent invocation — reviewer is "
        "invoked by /ship orchestrator, not by the implementer)."
    ),
    # ADR-0046: codebase-critic + parsimony reframe
    "PIP-011": (
        "The gate on adding a critic is a parsimony principle (minimize critics; each "
        "earns its place against a distinct concern no existing critic absorbs) — not a "
        "numeric count cap."
    ),
    "PIP-012": (
        "`codebase-critic` provides per-PRD macro review covering: (1) semantic doc "
        "currency, (2) architectural drift, (3) refactoring opportunities; BLOCK for "
        "PRD-introduced drift, RECOMMEND for improvements."
    ),
    "PIP-013": (
        "`codebase-critic` fires once per PRD at the last open slice, before that "
        "slice's reviewer pass, judging the cumulative PRD diff; reviewer remains "
        "the sole merge gate."
    ),
    # -----------------------------------------------------------------------
    # hooks scope (ADR-0015, ADR-0023, ADR-0033, ADR-0057)
    # -----------------------------------------------------------------------
    # ADR-0015: hooks adoption — D1 (config location) + D2 (scope policy)
    "HOK-001": (
        "Project-wide Claude Code hooks are configured in `.claude/settings.json` "
        "under the `hooks` section; per-developer overrides via `.claude/settings.local.json` "
        "are not used by default (ADR-0015 D1)."
    ),
    "HOK-002": (
        "Hooks are limited to three permitted categories: logging (write to local files), "
        "validation (exit-code block/ask), and notification (stderr message). "
        "Hooks MUST NOT auto-invoke Claude Code skills or subagents (ADR-0015 D2, source=CLAUDE.md #12)."
    ),
    # ADR-0023: validation + notification hooks — D3 (pre-tool-edit) + D4 (bash-block) + D5 (prompt-nudge)
    "HOK-003": (
        "A PreToolUse(Edit|MultiEdit|Write) hook mechanically escalates rule #10 "
        "(main-agent meta-output discipline): it emits `permissionDecision: \"ask\"` "
        "when the main agent attempts to write a tracked file, unless the write is in a "
        "subagent context (ADR-0023 D3)."
    ),
    "HOK-004": (
        "A PreToolUse(Bash) hook blocks `git push origin main` (any flavor) with "
        "`permissionDecision: \"deny\"`, enforcing rule #4 at the session level (ADR-0023 D4)."
    ),
    "HOK-005": (
        "A SessionStart hook injects live workflow state (branch, divergence vs origin/main, "
        "open slices, open PRs, open captured items) into every new session's context, "
        "mitigating the stale-worktree false-alarm pattern (ADR-0023 D2)."
    ),
    # ADR-0033: tooling-spawn — D1 (fourth category) + D2 (skill/subagent exclusion preserved)
    "HOK-006": (
        "A fourth hook category is permitted: **tooling-spawn** — hooks may spawn "
        "project-local tooling processes that meet ALL FOUR criteria: no LLM API calls, "
        "localhost-only binding, project-scoped script, idempotent spawn check (ADR-0033 D1)."
    ),
    "HOK-007": (
        "The tooling-spawn carveout does NOT authorize hook scripts to invoke "
        "`.claude/skills/` skills or `.claude/agents/` subagents. ADR-0015 D2's core "
        "intent — preventing hooks from auto-billing the user via LLM calls — is "
        "preserved unchanged (ADR-0033 D2)."
    ),
    # ADR-0057: fail-loud + context-injection — D1 (fail-loud) + D4 (fifth category)
    "HOK-008": (
        "Every hook script MUST emit an attempt beacon BEFORE any parsing or branching; "
        "on any internal error it MUST emit an ERROR beacon to `hook-fires.jsonl` rather "
        "than exiting silently; payloads are parsed in full via python3 — never truncated "
        "with `head -c` (ADR-0057 D1, fail-loud contract)."
    ),
    "HOK-009": (
        "A fifth hook category is permitted: **context injection** — a SessionStart hook "
        "MAY inject deterministic, read-only command output into session context. The hard "
        "line is unchanged: hooks NEVER auto-invoke skills or subagents (ADR-0057 D4, "
        "source=CLAUDE.md #12)."
    ),
    # -----------------------------------------------------------------------
    # slicing scope (ADR-0005, ADR-0013)
    # -----------------------------------------------------------------------
    # ADR-0005: output-shape + slicing methodology — D2 (slicing methodology) + D3 (cascade-doc)
    "SLI-001": (
        "Slice 1 of every multi-slice PRD MUST be a walking-skeleton — it cuts through "
        "every pipeline layer end-to-end (hamburger method), even if crudely; building one "
        "layer completely before another is explicitly rejected (ADR-0005 D2, source=CLAUDE.md #2)."
    ),
    "SLI-002": (
        "When a slice approaches the LoC cap, the slicer uses SPIDR split-fallback hints "
        "(Spike / Path / Interface / Data / Rules); S, I, and R are the dominant splits for "
        "this agent-workflow domain (ADR-0005 D2)."
    ),
    "SLI-003": (
        "For each candidate decomposition, the slicer MUST identify cascade-docs — files "
        "that should update to reflect the new feature even when not strictly required by "
        "acceptance criteria — and add a slice or merge coverage for each; the slicer-critic "
        "enforces this check (ADR-0005 D3, source=CLAUDE.md #16)."
    ),
    # ADR-0013: N=1 degenerate carveout — D1 (slicer self-restraint) + D2 (critic acceptance)
    "SLI-004": (
        "When all N candidate decompositions would produce bit-identical post-merge end-state "
        "(same files, same LoC, same content — modulo commit ordering), the slicer declares "
        "N=1 with explicit rationale instead of fabricating cosmetic variation; N=3 remains "
        "the default for genuinely-open-shape PRDs (ADR-0013 D1)."
    ),
    "SLI-005": (
        "The slicer-critic accepts N=1 with explicit rationale as a legal input; it verifies "
        "the rationale answers: which PRD section locks the shape, which variation axis was "
        "rejected, and whether N=3 would have produced genuinely-different alternatives "
        "(ADR-0013 D2/D3)."
    ),
    # -----------------------------------------------------------------------
    # verification scope (ADR-0037, ADR-0040, ADR-0050)
    # -----------------------------------------------------------------------
    # ADR-0037: production-verify gate — D1 (mandatory gate) + D2 (auto-routing) + D4 (PRD declares)
    "VER-001": (
        "After all slices of a feature merge, a mandatory, blocking production-verification "
        "gate runs before the feature is 'done'; PASS → feature done; FAIL → gate BLOCKS; "
        "per-feature granularity (not per-slice) (ADR-0037 D1, source=CLAUDE.md #15)."
    ),
    "VER-002": (
        "`qa-tester` in production-verify mode auto-routes by change type: "
        "browser UI (`dashboard/*`) → headless Playwright; hooks/settings → synthetic-payload "
        "fire + log assertion; skills/tools → command run + output assertion; "
        "docs/ADRs → static grep (ADR-0037 D2)."
    ),
    "VER-003": (
        "Every PRD §2 must include a 'Production check:' line stating what to exercise and "
        "the expected result; `prd-critic` BLOCKs a PRD whose production-check line is "
        "missing or non-actionable (ADR-0037 D4)."
    ),
    # ADR-0040: QA residual model — D1 (residual model) + D2 (non-blocking) + D5 (fidelity)
    "VER-004": (
        "The machine attempts every PRD §2 criterion; a criterion it cannot faithfully "
        "verify returns PROVISIONAL and becomes a human residual posted as a "
        "`needs-human-check` issue — the residual is discovered empirically, not predicted "
        "at plan time (ADR-0040 D1)."
    ),
    "VER-005": (
        "The human residual does NOT block PRD closure; the PRD auto-closes on machine "
        "PRODUCTION_VERIFY: PASS alone; a machine-confident FAIL still blocks per ADR-0037 "
        "D5 loop; the `/qa-review` skill clears residuals on the human's own cadence "
        "(ADR-0040 D2/D4)."
    ),
    "VER-006": (
        "`qa-tester` browser route MUST drive real interaction — `page.click()`, "
        "`page.fill()`, `page.goto()` — and assert on what a human sees; `page.evaluate()` "
        "is a last-resort disambiguator only; eval-only proof → PROVISIONAL, not PASS "
        "(ADR-0040 D5)."
    ),
    # ADR-0050: headless Playwright driver — D1 (driver choice) + D2 (tool boundary)
    "VER-007": (
        "Headless Playwright/Chrome (`headless=True`, `channel='chrome'`) is the qa-tester "
        "browser driver for ui-mode and the production-verify browser route; it replaces "
        "Claude_Preview MCP, eliminating the OS-visibility timeout by rendering offscreen "
        "(ADR-0050 D1)."
    ),
    "VER-008": (
        "The qa-tester browser route is driven entirely via `Bash` (write a Python script to "
        "a tmp path via heredoc, execute it, read results); all `mcp__Claude_Preview__*` "
        "calls are dropped; no tracked files are written by the qa-tester (ADR-0050 D2)."
    ),
    # -----------------------------------------------------------------------
    # commits scope (ADR-0001)
    # -----------------------------------------------------------------------
    # ADR-0001: foundational design — D12 establishes Conventional Commits + never-push-main
    "COM-001": (
        "Every commit message follows `<type>(<optional scope>): <subject>` "
        "(Conventional Commits); subject is lowercase; subject line is capped at ≤72 chars; "
        "types: feat/fix/docs/chore/refactor/test/perf/style/build/ci "
        "(ADR-0001 D12, source=CLAUDE.md #5)."
    ),
    "COM-002": (
        "Every agent-authored commit MUST carry a `Co-Authored-By: Claude …` trailer; "
        "`Closes #<slice-issue>` belongs in the PR body, NOT the commit subject; "
        "the git log is the changelog — no separate CHANGELOG file "
        "(ADR-0001 D12, source=CLAUDE.md #5/#6)."
    ),
}


def _get_rule_statement(rule_id: str, adr_id: str) -> str:
    """Return a one-line statement for the given rule_id."""
    if rule_id in _RULE_STATEMENTS:
        return _RULE_STATEMENTS[rule_id]
    # Fallback: generic statement referencing the source ADR
    return f"Rule {rule_id} sourced from {adr_id} — see ADR for details."


# ---------------------------------------------------------------------------
# Digest rendering
# ---------------------------------------------------------------------------

def _render_scope(scope: str, adrs: list[dict]) -> str:
    """Render the .claude/rules/<scope>.md content for the given ADRs."""
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append(f"# {scope.capitalize()} rules\n")
    lines.append(
        f"Atomic rules for the `{scope}` scope, generated from non-superseded ADR "
        f"frontmatter by `tools/gen_rules.py`.\n"
    )

    for adr in adrs:
        adr_id = adr["id"]
        # ADR filename (relative, for linking)
        adr_file = adr["path"].name
        lines.append(f"\n## Source: {adr_id} (`decisions/{adr_file}`)\n")
        for rule_id in adr["rule_ids"]:
            statement = _get_rule_statement(rule_id, adr_id)
            lines.append(f"- **{rule_id}:** {statement}\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate(check_mode: bool = False) -> int:
    """
    Generate (or diff-check) .claude/rules/<scope>.md files.

    Args:
        check_mode: if True, compare fresh output to committed files and
                    exit non-zero if any differ (mirrors CHECK 2 behavior).

    Returns exit code (0 = success, 1 = failure/dirty).
    """
    adrs = _load_adrs()

    # Separate into active (non-superseded) and superseded
    active_adrs = [a for a in adrs if not _is_superseded(a)]

    if not active_adrs:
        print("gen_rules.py: no active ADRs with frontmatter found.", file=sys.stderr)
        return 0

    # Group by scope
    scopes: dict[str, list[dict]] = {}
    for adr in active_adrs:
        scopes.setdefault(adr["scope"], []).append(adr)

    # Ensure .claude/rules/ exists (unless check_mode)
    if not check_mode:
        RULES_DIR.mkdir(parents=True, exist_ok=True)

    any_dirty = False
    generated_files: list[str] = []

    for scope, scope_adrs in sorted(scopes.items()):
        content = _render_scope(scope, scope_adrs)
        out_path = RULES_DIR / f"{scope}.md"

        if check_mode:
            # Compare to committed file
            if not out_path.exists():
                print(
                    f"DIRTY: {out_path.relative_to(REPO_ROOT)} does not exist "
                    f"(run 'python tools/gen_rules.py' and commit)",
                    file=sys.stderr,
                )
                any_dirty = True
            else:
                committed = out_path.read_text(encoding="utf-8", errors="replace")
                if committed != content:
                    print(
                        f"DIRTY: {out_path.relative_to(REPO_ROOT)} differs from "
                        f"fresh gen_rules.py output "
                        f"(run 'python tools/gen_rules.py' and commit)",
                        file=sys.stderr,
                    )
                    any_dirty = True
                else:
                    print(f"CLEAN: {out_path.relative_to(REPO_ROOT)}")
        else:
            out_path.write_text(content, encoding="utf-8")
            rel = out_path.relative_to(REPO_ROOT)
            print(f"gen_rules.py: wrote {rel}")
            generated_files.append(str(rel))

    if check_mode:
        return 1 if any_dirty else 0

    if not generated_files:
        print("gen_rules.py: nothing to write.", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    check = "--check" in sys.argv
    sys.exit(generate(check_mode=check))
